### PR TITLE
MultithreadDeadlockFix

### PR DESCRIPTION
**Pull request by devil-tamachan**

### CODE REVIEW

**Comment by devil-tamachan** [comment]
Sample code (Susie plugin for MangaMeeya7.3):
https://github.com/devil-tamachan/ifmango.spi/blob/master/ifmango.cpp

Step1:
MangaMeeya -> thread1 -> GetPicture(ifmango.spi) -> libmango -> ThreadPool::getInstance(Address 0xAAAABBBB)
                       -> thread2 -> GetPicture(ifmango.spi) -> libmango -> ThreadPool::getInstance(Address 0xAAAABBBB)
                       -> thread3 -> GetPicture(ifmango.spi) -> libmango -> ThreadPool::getInstance(Address 0xAAAABBBB)
                       -> thread4 -> GetPicture(ifmango.spi) -> libmango -> ThreadPool::getInstance(Address 0xAAAABBBB)

Step2:
 image decode

Step3 (Deadlock):
MangaMeeya -> thread1 -> GetPicture(ifmango.spi) -> libmango -> ThreadPool::~ThreadPool -> m_threads[i].join(); <-- Deadlock

**Comment by devil-tamachan** [comment]
I build it by mingw32-w64.
MangaMeeya73.zip https://w.atwiki.jp/mangameeya/pages/48.html

**Comment by t0rakka** [comment]
Try thread_join_sync branch; it might help. The problem I see is that we might start "joining" before the threads are done sleeping.. this waits until all the threads have exited the main loop.

1. set stop flag
2. wait until everyone has stopped (!) <-- this is the New Step we added
3. join

There is 200 ms window where thread might still be sleeping while we already start joining them (block current thread until the one has exited its main function). It might be difference in mingw's std::thread implementation vs. Microsoft's but this should make the difference irrelevant.. :_D

Let me know if the branch helped.

**Comment by devil-tamachan** [comment]
I try thread_join_sync branch. Deadlock happened.

my debug code & output
system.hpp: 
#if 1
    //#define debugPrint(...) std::printf(__VA_ARGS__)
    #define debugPrint(...) \
      { \
        char c[512]; \
        sprintf( c, __VA_ARGS__ ); \
        OutputDebugStringA(c); \
      }

thread.cpp:


    ThreadPool::~ThreadPool()
    {
        debugPrint("ThreadPool::~ThreadPool()\n");
        m_stop = true;
        //m_condition.notify_all();
        //Sleep(10000);
        
        debugPrint("m_threads: %d\n", (int)m_threads.size());

        for(int i=0;i<m_threads.size();i++)
        {
          debugPrint("  thread(0x%08X).joinable() == %s\n", (DWORD)(get_native_handle(m_threads[i])), m_threads[i].joinable() ? "true" : "false");
          if(m_threads[i].joinable())
          {
        debugPrint("    +join()\n");
            m_threads[i].join();
        debugPrint("    -join()\n");
          }
        }

ThreadPool::thread()

...
                    std::this_thread::yield();
                }
            }
        }
          debugPrint("thread %d: 99\n", threadID);
          //_endthread();
    }


OUTPUT (not MultithreadDeadlockFix):
...
thread 1: 99
thread 2: 99
thread3: 99
thread4: 99
ThreadPool::~ThreadPool()
m_threads: 4
  thread(1).joinable() == true
    +join()
[Deadlock & Debugger freezed]

**Comment by t0rakka** [comment]
That is strange; the "99" print tells that the threads (all four) have exited. The print says the thread (1) is joinable but join() goes into infinite loop (hangs).

Does the mingw need the GCC's -mthreads flag and if it does, is it set? I am not familiar with this specific compiler (never used it).. that might be a rational explanation for the effect we are experiencing.

**Comment by t0rakka** [comment]
One thing that comes to mind is that the join is called after main function has been exited, it might be a problem on this specific std::thread implementation? If you can write a "snuff()" function for the thread pool, put the destructor code in it and call it before main exits.. then leave the destructor blank.

ThreadPool::~ThreadPool()
{
    // ... everything moved to ThreadPool::snuff() function ...
}

int WinMain(...)
{
  // ... your code ...
  ThreadPool::getInstance().snuff();
}

Something like that could force the thread termination and joining to be done BEFORE we exit main.. 

I'd try myself but can't reproduce.  xP

If it helps.. wow..

**Comment by t0rakka** [comment]
Found this, three years old but might be related: https://stackoverflow.com/questions/10915233/stdthreadjoin-hangs-if-called-after-main-exits-when-using-vs2012-rc

**Comment by devil-tamachan** [comment]
> I'd try myself but can't reproduce. xP
1. PC on.
2. Launch MangaMeeya & load images & Close MangaMeeya  x10 - x30 (MangaMeeya ends normally)
3. Launch MangaMeeya & load images & Close MangaMeeya xXXX (MangaMeeya ends with Deadlock always. I see a lot of MangaMeeya's zombie in procexp)

**Comment by t0rakka** [comment]
This is fixed on vs2015, 2017 and 2019 that's why I haven't experienced it.. also works on macOS, Linux, Android, iOS.. might be the mingw + Windows combination that brings this into play. Of course we want to write this in a way that "just works" .. the atexit callback calling snuff (needs a better name!) might do the trick.. I really would prefer to keep the TP as singleton.

**Comment by t0rakka** [comment]
I'll install the toolchain + write some tests later today and see if I can (interactively) reproduce the problem. I have a good feeling about what the problem is (see above). You can expedite this if you can assist (as you have the compiler, etc). if I know it's the join-after-main-exits, then the fix should be simple enough. 

I'm not near the Windows machine at the moment so will have a small delay before can get started myself.. but am eager to get this fixed. :_)

**Comment by devil-tamachan** [comment]
I tested snuff(). Deadlock happened.

test code
```
thread.hpp
    public:
        ThreadPool(size_t size);
        ~ThreadPool();
...
        void snuff();

thread.cpp

    ThreadPool::~ThreadPool()
    {
    }
    void ThreadPool::snuff()
    {
        m_stop = true;
        m_condition.notify_all();

        while (m_sleep_count > 0)
        {
        }

        for (auto& thread : m_threads)
        {
            thread.join();
        }

        deleteQueue(m_static_queue);
        delete[] m_queues;
    }
```

**Comment by t0rakka** [comment]
Installing MinGW-W64, Threads: WIN32 (not POSIX). Let me know if I should have picked POSIX threads.. :D

**Comment by t0rakka** [comment]
MSYS2 / g++ 9.1.0: normal threading and shutdown works OK. Must do more testing on exactly same environment you have..

**Comment by t0rakka** [comment]
It might not be toolchain specific at all; https://stackoverflow.com/questions/48809595/how-to-create-threads-in-dlls-c

The thread has to exit (terminate & join) before the PROCESS_DETACH.

You could snuff() the TP after getting one image, but of course, it wouldn't work for more than 1 image in that case. But: if that allows it to work, then we have something to work with.

**Comment by t0rakka** [comment]
https://devblogs.microsoft.com/oldnewthing/20070904-00/?p=25283

**Comment by devil-tamachan** [comment]
I stopped compiling with mingw32-w64. Maybe it won't happen with VC2019. (testing now)

I tried the following (all failed)
1.  Disable DLL_THREAD_* (Exit all mango's threads. However, main thread's deadlock)
```
    case DLL_PROCESS_ATTACH:
    
      {
        HMODULE hModule = NULL;
        GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS|GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT, (LPCSTR)DllMain, &hModule);
        DisableThreadLibraryCalls(hModule);
      }
      break;
```

2.  Add Dll's ref count (Exit all mango's threads. However, main thread's deadlock)
```

    void ThreadPool::thread(size_t threadID)
    {
        HMODULE hModule = NULL;
        GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS, (LPCSTR)get_native_handle, &hModule); //add dll's ref count
        
...

        FreeLibraryAndExitThread(hModule, 0);
    }
```

Env: mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0
Compile (without MSYS):
1. Run C:\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw-w64.bat
2. cd mango\build
3. mkdir build32
4. cd build32
5. cmake -G "MinGW Makefiles" ..
6. mingw32-make

Thank you very much for your help :) > t0rakka

**Comment by t0rakka** [comment]
I am not entirely clear on if the call (2) in ThreadPool::thread() originates from the DLL or the main application which use loaded the DLL with LoadLibrary. The main thing here is that the FreeLibraryAndExitThread MUST be called from the main application which has loaded the DLL in the first place.

The thing that is happening here, that I suspect, is that the DLL has it's own instance of the ThreadPool and main application has it's own, which is not a problem per se, but waste of resources and root cause for the problem: that we try to join a thread while the mutex the thread join used in Windows Kernel is already locked by the main application unloading the DLL.

I think I might have a decent work-around for this scenario.

What if, I make it possible to the caller to provide your own ThreadPool instance that overrides the one initialized automatically by the ThreadPool::getInstance(). Something like, ThreadPool::setInstance() static member function?

You could do in your main program:

ThreadPool *tp = new ThreadPool(N);
ThreadPool::setInstance(tp);
...
delete tp; // you could control when this happens... (feel free to use std::unique_ptr but careful when it goes out of scope.. might skew the timing if used carelessly ;)

OK, that should give you the control..!

The next thing is that if the DLL has it's own instance of the ThreadPool, you can pass the tp pointer to the DLL and setInstance it there so now the TP is 100% shared between DLL and MAIN.

I should just be careful to NEVER delete user-set instance, or, require you to set nullptr to the instance to disable "auto-delete" on it, whichever makes more sense (have to think about that a second, probably obvious when writing the code). I think it is safe to say that after user has set custom instance, I should NEVER, EVER automatically create one after that (as happens now).

Apologies if the DLL does share the instance already, not sure if that is happening .. but from the problem at hand it looks like the DLL's instance is shutting down at DLL unload and that's what is causing the problem to begin with. I don't see how this could otherwise happen if you are calling the FreeLibrary or FreeLibraryAndExitThread from MAIN.. the singleton deletion code should be something that runs LAST in MAIN, after your explicit calls to the FreeLibrary* .. so.. that's why I suspect the DLL has it's own instance. I could be wrong. :)

I was going to make a MAIN/DLL test case for Windows this weekend but got distracted. I'll see if the custom setInstance helps making life more fun in Windows side..

**Comment by t0rakka** [comment]
OK; tested - created server.exe and client.dll, the server does:

WinMain()
{
    1. module = LoadLibrary("client.dll")
    2. magic = GetProcAddress(...)
    3. mainloop, calls magic as rapidly it can.. :_D
    4. FreeLibrary(module)
}

The magic() is a simple function that just loads image, returns.. this triggers TP creation. The TP is destroyed after WinMain exits..

There is one instance of TP in the process, shared by the server.exe and client.dll, it is created when the magic() is called for the first time and as said, deleted after WinMain returns. Works A-OK with Visual Studio 2019 Community Edition.

I was prepared for doing all the API refactoring mentioned in earlier comment but so far things work as they are intended.. notice: this is a plain FreeLibrary call, no ExitThread EX stuff used. This works alright as we don't try to join any threads while the DLL is being released.

So far so good. The next test is to see what happens when we link with the client.lib and let the DLL to be loaded automatically by the linker. I am assuming this is the problematic scenario.. to be continued..

**Comment by t0rakka** [comment]
Linker-loaded client.dll also works OK with Visual Studio 2019. The static is deleted after WinMain and DLL-unload.

Could just be "works on my machine" -effect; let me know if still need the manual TP management.

**Comment by t0rakka** [comment]
Loading bitmaps in WinMain creates another TP as predicted; DLL and MAIN have their own instances. It still works, but is wasteful. I'll implement the TP sharing for applications that want/can be smart about this. :)

**Comment by t0rakka** [comment]
new ThreadPool(N) gives a compiler warning for alignas if not using at least c++17, which added support for alignas in heap allocations. It's possible to use aligned_malloc and call constructor to the raw storage but blah.. :_D   At first, I was going to simply use std::unique_ptr as storage but allocation from another heap doesn't play well with std. The best design choice related to Windows in this case would be just to store the raw pointer and leave management to the caller.

One way to work around the multiple heaps / multiple instances of TP in same process is to do everything on one side and have custom DLL-boundary-crossing API to leverage that arrangement. One has to take this into consideration with all memory allocations anyway; you just don't return std::string's over DLL boundaries anyway, right? =)

**Comment by devil-tamachan** [comment]
I am hard to read english...
VC2019 has worked well so far. Maybe MinGW-w64 (or VC6's msvcrt) is bad.

**Comment by t0rakka** [comment]
Still, it's good to know there is a problem. I would prefer to address it with heap-allocated ThreadPool, which can also be user-managed but to make life simpler I would prefer to use C++17 for that as it supports the alignas for heap allocations. Otherwise would have to write unnecessary band-aid to make it happen.. 

Hey, thanks for reporting this & glad that it works now (even though it is a bit of a work-around).

**Pull request closed without merging**
