### PR TITLE
AddDisableSwitch

### PR DESCRIPTION
**Pull request by devil-tamachan**

### CODE REVIEW

**Comment by devil-tamachan** [comment]
I committed configure.hpp.

**Comment by t0rakka** [comment]
Same comment about the ARCHIVE enables. The -D's should modify the defaults. It's getting awfully fine-grained / specific which code is compiled in.. :_D 

You are trimming the library size for mobile or some otherwise limited storage / memory use situation?

At one point I was pondering making some of the components separate libraries, but there is one platform where it is super inconvenient (macOS / Xcode). It's less hassle to bundle everything into one Framework and drag'n'drop it to new project. Most of the weird design choices have been made as concessions for macOS.. and then they semi-deprecate C++ and OpenGL.. but lets not go into that topic now.

**Comment by t0rakka** [comment]
Added a small tweak: added ENABLE_ARCHIVE_RAR to make things more symmetric and it requires the GPL license to be enabled. It could also give some value to be able to disable compilation of some external libraries like Google's libwebp when it is not used. TODO for later.. linker might prune those out anyway but I wouldn't bet on it.

**Comment by devil-tamachan** [comment]
CMake's MANGO_DISABLE_LICENSE_GPL(ENABLE/DISABLE_ARCHIVE_RAR) is not worked now. Please fix CMakeLists.txt.

**Comment by t0rakka** [comment]
// [ configure.hpp ]
#if !defined(MANGO_DISABLE_ARCHIVE_RAR) && defined(MANGO_ENABLE_LICENSE_GPL)
    #define MANGO_ENABLE_ARCHIVE_RAR
#endif

The ARCHIVE_RAR requires GPL license to be active.. is the problem that the RAR support won't be activated, or is activated when it shouldn't be activated?

I grep for all instances of MANGO_ENABLE_ACHIVE_RAR in the sources and the only place where it is set is configure.hpp, see above. It will NOT be set if the GPL license is not enabled.. and it won't be enabled if the disable it set.

What's the exact problem? Won't enable or won't disable, when it should?

**Comment by t0rakka** [comment]
Ah, I see.. the MANGO_DISABLE_ARCHIVE_RAR was not in CmakeLists.txt .. disabling GPL disabled it, though. Should be good now.. let me know if didn't fix..

**Pull request merged**
