### PR TITLE
Initial CMake/CMakeLists integration

### PR DESCRIPTION
**Pull request by fuchstraumer**
This is my first attempt at getting CMakeLists working with this project - I've tested building it on Windows and Ubuntu 17.10 thus far, and can test it on Mac OSX later today potentially.

Note the compile features that have been added, to replicate flags I found in the `.vcxproj` and `makefile`. I set some of the math options as options, but the most common ones will default to on (using fast floating point, enabling AVX2 support). Not sure if the AVX512 one will work, but I think it should?

There are some notes on using this:
- Installing might yet be funky, but the way I set it up is how my "VulpesRender" repo is setup. Linking to that is as simple as using `ADD_SUBDIRECTORY()` and then linking to "VulpesRender" in parent projects. So, this should make using this library as a dependency much easier!
- CMake defaults to creating a makefile for debug on Unix. To create a makefile for release, something like the following command should be used: `cmake -DCMAKE_BUILD_TYPE=RELEASE ../` (assuming you're in a directory for the build files to be written to, like `build-cmake`
- I did not include the `GUI` elements/subfolder. I wasn't sure how to quite set up the various options and flags that would choose the final set of `.cpp`/`.hpp` files to link into the project. I can do that later, if needed, or you might be better prepared to handle it yourself
- I moved the external library header files into `include`, so that I could just use a single `INSTALL` command in the CMakeLists to get all of our headers moved to the right spot when that time comes. It bumped the number of files changed a bunch, sorry!
- Also had to many of the external library source files to account for the new pathing :/

I'm not sure I'd merge this into master yet, but it's certainly ready for testing \^^

Also I'm worried some of the large diffs might be due to my IDE trying to change the spacing - I use 4 spaces (transformed from a single tab press, though) so hopefully that's what you use too. Hopefully this works nicely for you!

### CODE REVIEW

**Comment by t0rakka** [comment]
I'll have to upgrade and test the new include paths in Visual Studio and XCode. I lefty my Macbook at work so allow 24 hours of delay for this operation. :)

**Comment by t0rakka** [comment]
I created a new branch from the cmake tests; "cmake" and noticed a few issues while catching up with the other build systems.

1. The library is built as static library (that's fine) and installed into /usr/local/lib (fine)
2. The headers are installed into /mango/, which is not fine
3. The external headers do not need to be installed
4. The code is compiled as "-O0" (default), -O2 should be the minimum and -O3 or fast recommended
5. It would be cleaner if the CMakeLists.txt could live under build/ but is OK
6. I would prefer if the external libraries had their source+includes in the same place (following the libraries original fs layout) .. it should be possible to add the source/external to INCLUDE path with cmake
7. The change to use INCLUDE in the .c files was good; the "../../" stuff was mostly unnecessary but I think the best way to go ahead is to keep the headers where they were (just fix them to assume the include paths are correctly set up)

The layout for the external ("3rd party") files should be kept as it is. I would submodule them if I didn't have modifications that I don't want to upstream and don't really want to fork myself for that. I want to keep everything as one bundle. Xcode / macOS is the biggest reason for the layout as on that environment I build everything as a framework that is ready to be drag-dropped to any project easily.

It's also a small wart that you have to "know" the name of the cmake build folder so that the gitignore fille correctly ignore the files. I did "cmake .." from the "correct place" and it built quite nicely. Typically my machine compiles the files for 6.5 seconds but the cmake generated Makefile did the job in 2.4 seconds so that got me wondering if the optimization settings are same (O2, O3 or Ofast) - they weren't (see above).

"oops" ; I merged to a new branch so CRs went that way.. I try to sort out build issues on Visual Studio and Xcode meanwhile to get things up to speed. Android build worked out of the box with the changes.

**Comment by t0rakka** [comment]
I created a "cmake2" branch where I modified the CMakeLists.txt from this branch so that it fits better with the existing infrastructure. I had to add "../" there so reflect the changed position of the script in the tree. I haven't looked at the remaining issues yet. For now I need feedback on does that layout work for you. The place of CMakeLists.txt is not that critical but this is cleaner because then all build scripts are under build/ (for me, need to know if it is convenient for your uses).

Current Usage:
    cd build/cmake
    cmake ..
    make -j10

Let me know if we can go ahead with this arrangement or let me know why it's not feasible. I am complete CMake n00b and probably not aware of all of the side effects at play. :)

You probably want your contribution to show up so it's fine by me if you create a PR from any of the branches (cmake, cmake2) for round-trip back to master when we have everything settled. I goofed up a bit when merged into a new branch (sorry!) to be able to work on the changes from multiple machines.

Good News (?) is that the .c and .cpp files compiled as-is w/o any modifications with the latest arrangement. I still want to kill unnecessary "../../" 's, of course to keep things tidy, that was a very good job, thanks for spotting! The external .c files can use relative paths since those headers will NOT be exposed to external use.

To be continued.. & let me know if I completely butchered the intent..

**Comment by t0rakka** [comment]
The "cmake2" branch should have most of the issues listed (2-6) fixed. 

I found out that the ARM build doesn't work without some extra flags. The GCC 7.2 on ARM complains about ARM's own headers without -fpermissive and some other issues. This is not critical since I build for ARM with cross compile toolchains anyway (not on-device, but the old makefile setup allows that but yeah, it's quite hacky and hard to maintain). Eventually it would be great if all command-line compilation would just use cmake. :)

I just googled for solutions to the issues so I don't want it to look like I know what I am doing. ;--)

**Comment by t0rakka** [comment]
Let me know how the "cmake2" head works for you. I'm still not done with it and PRs are welcome on top of it. I'll try to not merge them before feedback. I just got excited and carried away up there. Sorry again.

**Comment by fuchstraumer** [comment]
No need to apologize! I'm glad you got excited by all of this, at least. I was out last night and busy dealing with some other stuff going on after I submitted this PR, so it's nbd. I hope the CMakeLists I wrote at least served as an outline on how to get started - that's really the most important thing you can get with CMake, imo. So you didn't butcher the intent at all - this was just to make it easier for people to play with platform/compiler combinations and hopefully make using it in other projects easier, too. `ADD_SUBDIRECTORY` is a wonderful wonderful thing to have available for this project

I'll give the branch a try when I am able to :)

**Comment by t0rakka** [comment]
Nice to hear that. I have ARM boards to play with so I'll fix the issues there and add more platforms that way. The build script would otherwise work already out-of-the-box but these are workarounds that are needed for platform's own headers to work with the latest compilers.

**Pull request merged**
